from pathlib import Path


ROOT = Path(__file__, "..", "..").resolve()
DATA_VERSION_V0 = "v0"
METADATA_REPO = Path(ROOT, "btp-service-metadata", DATA_VERSION_V0).resolve()
METADATA_REPO_DEVELOPERS = Path(METADATA_REPO, "developer").resolve()

FOLDER_TEMPLATES = Path(ROOT, "templates").resolve()

FOLDER_OUTPUT_DOCS = Path(ROOT, "docs").resolve()
FOLDER_OUTPUT_DOCS_MD = Path(FOLDER_OUTPUT_DOCS, "md").resolve()
FOLDER_OUTPUT_DOCS_HTML = Path(FOLDER_OUTPUT_DOCS, "html").resolve()

TEMPLATE_DEVELOPERS_MD = Path(FOLDER_TEMPLATES, "SERVICE-DETAILS.MD").resolve()
TEMPLATE_DEVELOPERS_HTML = Path(FOLDER_TEMPLATES, "SERVICE-DETAILS.HTML").resolve()

# service categories
CATEGORIES = {}
CATEGORIES["SERVICE"] = ["SERVICE", "ELASTIC_SERVICE", "PLATFORM"]
CATEGORIES["APPLICATION"] = ["APPLICATION", "QUOTA_BASED_APPLICATION"]
CATEGORIES["ENVIRONMENT"] = ["ENVIRONMENT"]
