name: Fetch BTP service metadata
# This action executes the following up actions needed after an update of the metadata happened
# 1. Fetch the BTP service metadata from the btp-service-metadata every day at 7am UCT
# 2. Generate the documentation as markdown

on:
  schedule:
      - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  update-metadata-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      # Install python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install python packages
        run: |
          cd scripts
          pip install -r requirements.txt

      - name: Execute generation of docs
        run: |
          cd scripts
          python3 getdata

      - name: Commit and push changes
        run: |
          git add -A
          git config user.email "mydocubot@users.noreply.github.com"
          git config user.name "[my docu bot] docu generation"
          git diff --quiet && git diff --staged --quiet || git commit -m "[my docu bot] Generate parameter documentation"
          git push
